### ISSUE TITLE
Cannot retrieve child components passed in via slots

### ISSUE THREAD

**Issue by albarivas** [salesforce/sfdx-lwc-jest#176]
### Description
I have a couple of tests that fail with the upgrade to API 50 and sfdx-lwc-jest version 0.10.1. They're all failing because of the same issue. Before, the test able to retrieve a child component passed in via a slot, and now it is not.

#### Steps to Reproduce
Example:

tabsWrapper.html
```
<template>
    <c-example-wrapper
        icon-name="custom:custom44"
        lwc="tabs"
        title="Tabs"
        visualforce="tabs"
        visualforce-height="60px"
    >
        <c-tabs slot="lwc"></c-tabs>

        <!-- prettier-ignore -->
        <p>
            Use <a target="_blank" href="https://developer.salesforce.com/docs/component-library/bundle/lightning-tabset">
            lightning-tabset</a> and <a target="_blank" href="https://developer.salesforce.com/docs/component-library/bundle/lightning-tab">
            lightning-tab</a> to replace apex:tabPanel and apex:tab.
        </p>
    </c-example-wrapper>
</template>
```

```
    it('shows inner component using c-example-wrapper', () => {
        const element = createElement('c-tabs-wrapper', {
            is: TabsWrapper
        });
        document.body.appendChild(element);

        // Verify required child components are present on render.
        const exampleEl = element.shadowRoot.querySelector('c-example-wrapper');
        expect(exampleEl).not.toBeNull();

        // THIS QUERYSELECTOR WAS WORKING BEFORE; BUT NOW RETURNS NULL
        const innerEl = exampleEl.querySelector('c-tabs');
        expect(innerEl).not.toBeNull();
    });
```

I've tried to do `exampleEl.querySelector('*');`, and the standard child HTML elements are being returned (one `p` and two `a`), however the custom component is not returned.

You can see all the tests that fail because of this issue in [this PR](https://github.com/trailheadapps/visualforce-to-lwc/pull/88). 
 
# Command to repro
Run the test, I'm running it with `npm run test:unit`

#### Expected Results
The test passes

#### Actual Results
The test fails because the inner element cannot be found. Additionally, the following error comes up:

[LWC error]: Ignoring unknown provided slot name "lwc" in [object:vm ExampleWrapper (1)]. Check for a typo on the slot attribute.
      <c-example-wrapper>

      at logError (node_modules/@lwc/engine/dist/engine.cjs.js:935:13)
      at validateSlots (node_modules/@lwc/engine/dist/engine.cjs.js:5471:7)
      at node_modules/@lwc/engine/dist/engine.cjs.js:5534:9
      at ReactiveObserver.observe (node_modules/@lwc/engine/dist/engine.cjs.js:825:7)
      at isUpdatingTemplate (node_modules/@lwc/engine/dist/engine.cjs.js:5501:9)
      at runWithBoundaryProtection (node_modules/@lwc/engine/dist/engine.cjs.js:6410:5)
      at evaluateTemplate (node_modules/@lwc/engine/dist/engine.cjs.js:5484:3)
      at invokeComponentRenderMethod (node_modules/@lwc/engine/dist/engine.cjs.js:5683:39)

### Version
-   @salesforce/sfdx-lwc-jest: 0.10.1
-   Node: 12.15.0

**Comment by albarivas** [comment]
@pozil @jodarove this maybe an issue with the engine

**Comment by jodarove** [comment]
@albarivas @pozil i took a look to your issue. Turns out that `exampleWrapper` is being mocked [here](https://github.com/trailheadapps/visualforce-to-lwc/blob/master/force-app/main/default/lwc/tabsWrapper/__tests__/tabsWrapper.test.js#L5) and [the mock template](https://github.com/trailheadapps/visualforce-to-lwc/blob/master/force-app/main/default/lwc/exampleWrapper/__mocks__/exampleWrapperTemplate.html) does not provides an slot named "lwc", that's why you are seeing `[LWC error]: Ignoring unknown provided slot name "lwc" in [object:vm ExampleWrapper (1)]. Check for a typo on the slot attribute.`

You either remove the `jest.mock('../../exampleWrapper/exampleWrapper');` or add the named slot to the mock template.

The reason you didn't got this error before, and you do now with the pr, is because your tests were running in native shadow (the setupFilesAfterEnv in sfdx-lwc-jest is the one that install the synthetic shadow)

cc/ @pmdartus

**Comment by jodarove** [comment]
ill close this issue, feel free to re-open if you think otherwise

**Comment by pozil** [comment]
Thanks for the detailed explanation @jodarove, this is very helpful.

**Comment by albarivas** [comment]
Thank a lot!

Alba Rivas
Lead Developer Evangelist | Salesforce <http://salesforce.com/>
+34663450988
@AlbaSFDC <https://twitter.com/AlbaSFDC>
<http://sfdc.co/trailheadsignature>
