### ISSUE TITLE
Latest npm version re-introduces wrong API version check

### ISSUE THREAD

**Issue by muenzpraeger** [salesforce/sfdx-lwc-jest#199]
### Description
The `latest` version from `npm` (`0.11.0` as of writing this) still uses API version `50.0` as baseline.

`Invalid sourceApiVersion found in sfdx-project.json. Expected 50.0, found 51.0`

This looks like a regression as the Spring '21 pre-release version `0.10.4` works.

#### Steps to Reproduce

1. Change a SFDX projects API version to `51.0` (Spring '21)
2. Install `@salesforce/sfdx-lwc-jest@latest` from `npm`.
3. Run Jest tests

#### Expected Results

Tests run successful.

#### Actual Results

The Jest invocation exists with `Invalid sourceApiVersion found in sfdx-project.json. Expected 50.0, found 51.0`.

### Version

-   @salesforce/sfdx-lwc-jest: 0.11.0

**Comment by ctchipps** [comment]
Also experiencing this issue

**Comment by ravijayaramappa** [comment]
The tags have been fixed. Currently
```
0.10.4 latest
0.10.2 winter21
0.11.0 next
```

Will close this issue. Please reopen if your issue is not resolved.

**Comment by ctchipps** [comment]
@ravijayaramappa When using 0.10.2, I am still receiving `Invalid sourceApiVersion found in sfdx-project.json. Expected 51.0, found 50.0`. I am using 50.0 in my sfdx-project.json.

**Comment by ravijayaramappa** [comment]
@ctchipps Before addressing your question: `0.10.2` maps to winter'21. This was the previous release. Is that the version you specifically want to use? 
`0.10.4` is the version that maps to Spring'21 which is in production now. The ApiVersion for this release is 51.0.

From your error message, it appears that your installed version of sfdx-lwc-jest is 0.10.4. It might be that your the version in your package string might be `~0.10.2` and it is installing 0.10.4 because of the `~`. Can your confirm that you are indeed running  v0.10.2 using this command in your project root `npm list @salesforce/sfdx-lwc-jest`?
