### ISSUE TITLE
lwc jest not working with Optional Chaining

### ISSUE THREAD

**Issue by AllanOricil** [salesforce/sfdx-lwc-jest#241]
### Description

I generated jest test using the following sfdx command 

`sfdx force:lightning:lwc:test:create -f PATH_TO_COMPONENT_JS`

And when I tried to run it I got the following "Syntax Error" for using the Safe Navigation Operator

![image](https://user-images.githubusercontent.com/55927613/127154148-865366ee-32c5-4041-9c68-f778fd6186d6.png)

The component I posted below works without a problem.

#### Steps to Reproduce

````html
<template>
    <div class="questionnaire">
        <template for:each={questionnaire} for:item="entry">
            <div key={entry.Prompt} class="question">
                <p>{ entry.Prompt }</p>
                <div class="options">
                    <template for:each={entry.Options} for:item="option">
                        <p key={option.value} class={option.class}>
                            { option.name }
                        </p>
                    </template>
                </div>
            </div>
        </template>
    </div>
</template>

````

````js
/*eslint-disable @lwc/lwc/no-inner-html, no-unused-vars, consistent-return*/

/*eslint-disable @lwc/lwc/no-inner-html, no-unused-vars, consistent-return*/

import { LightningElement, wire, api } from 'lwc';
import { getRecord } from 'lightning/uiRecordApi';

export default class TroubleshootFlowResult extends LightningElement {
    @api
    recordId;

    questionnaire = [];

    @wire(getRecord, {
        recordId: '$recordId',
        fields: ['Case.Question_Sheet__c']
    })
    getCaseQuestionnaire(result) {
        if (!result.data?.fields.Question_Sheet__c.value) return;
        this.questionnaire = this.prepareQuestionnaire(
            result.data.fields.Question_Sheet__c.value
        );
    }

    prepareQuestionnaire(questionnaire) {
        //salesforce encodes double quotes when using wire
        questionnaire = JSON.parse(questionnaire.replace(/&quot;/g, '"'));

        questionnaire.forEach((entry) => {
            entry.Options.forEach((option) => {
                option.class =
                    option.value === entry.Value ? 'option answer' : 'option';
            });
        });

        return questionnaire;
    }
}

````

Generated unit test which just mounts the component

````js
import { createElement } from 'lwc';
import TroubleshootFlowResult from 'c/troubleshootFlowResult';

describe('c-troubleshoot-flow-result', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        const element = createElement('c-troubleshoot-flow-result', {
            is: TroubleshootFlowResult
        });
        document.body.appendChild(element);
        expect(1).toBe(2);
    });
});
````

#### Expected Results

Safe Navigation Operator should not throw a "Syntax Error"

#### Actual Results

Safe Navigation Operator is throwing a "Syntax Error"

### Version

-   @salesforce/sfdx-lwc-jest: 
              0.9.2
              0.14.0
              1.0.1
              
-   Node: 12.13.0

**Possible Solution**

**Additional context/Screenshots**

**Comment by AllanOricil** [comment]
This stackexchange post is also talking about it

https://salesforce.stackexchange.com/questions/342361/jest-not-supporting-optional-chaining-operator

**Comment by AllanOricil** [comment]
Ok, the problem is the Node version. I changed to node 14 and the issue was fixed. I recommend you update this README and also this [official doc](https://developer.salesforce.com/docs/component-library/documentation/en/lwc/lwc.unit_testing_using_jest_installation)  page to say that it only works with Node 14 or above. At the moment that page only says that is recommended to use the LTS, but it does  not say I can't use, for instance, Node 12. This package could also display an error/warning advising people to update to Node 14 or above when running the tests or during the installation.

**Comment by AllanOricil** [comment]
I can't use 1.0.1 with Node 14 and because of that I can't fix the Optional Chaning syntax error, as the jest test is fixed with Node 14. 

![image](https://user-images.githubusercontent.com/55927613/127312379-d2ba28fa-6012-48e4-a0c9-c67b0d293c49.png)

**Comment by ekashida** [comment]
@AllanOricil Thanks for your feedback. From what I can tell, `sfdx-lwc-jest` does not use any features that require a specific version of node. This means that the issue that you encountered is really a local environment issue where the component used new language features that wasn't supported by the locally installed version of node.

As an important sidenote, you'll end up running into an issue where optional chaining will work during local development and testing using node v14 but will only work for browsers that support it in production. This is not an issue if you only support the latest versions of the evergreen browsers, but it will be an issue if you need to support older browsers (including but not limited to IE11). The reason for this is because LWC doesn't yet support optional chaining which was introduced in ES2020. As a reminder, this is the javascript that LWC does support: https://developer.salesforce.com/docs/component-library/documentation/en/lwc/lwc.get_started_supported_javascript

I do think it would be a good practice for this project to keep up to date with the current LTS version of node (as recommended by our own official docs) by specifying an LTS version via the `engines` field. [Note that even after this change, you will need local configuration that enforces this at installation time.](https://stackoverflow.com/questions/29349684/how-can-i-specify-the-required-node-js-version-in-package-json)

**Comment by AllanOricil** [comment]
@ekashida im pretty sure it is a node compatibility issue, and not just a "local" problem that I'm facing. I have tested this issue on windows 10 in two different PCs, with node 12, 13 and 14. 
After fixing the `sfdx-lwc-jest` version on 0.14.0, and varying the node version from 12 to 14, I got different issues with v12 and v13.
When using v13 this is the error I get , and on v12 is just the "syntax error" I described above

![image](https://user-images.githubusercontent.com/55927613/127399086-7055667a-143e-4e5d-85b5-756c9c10b015.png)

And when using node 14 the Optional Chainning syntax error is gone because it was officially supported by node (https://stackoverflow.com/questions/59574047/how-to-use-optional-chaining-in-node-js-12).

Anyway, someone else had the same problem on "salesforce.stackexchange" and nobody gave the guy a solution.

**Comment by ekashida** [comment]
That's correct, the issue was that an ES2020 feature was used in a version of node that didn't support it.

What I'm trying to say is that there's nothing to be fixed in the official docs--we can't predict which new features you decide to use in your component so we can't mandate which version of node you should use during development. What we can do is to let you know which javascript features are supported by LWC. Using this information, along with your supported browser matrix, you can decide which javascript features to use in your component and then appropriately adjust the version of your locally installed node binary.
