### ISSUE TITLE
uiRecordApi is missing implementation of utility functions

### ISSUE THREAD

**Issue by hagai-shatz** [salesforce/sfdx-lwc-jest#79]
It is impossible to test code that uses getFieldValue from uiRecordApi without reimplementing the function.
The mock for uiRecordApi in lwc-recipes includes the implementation of getFieldValue:
https://github.com/trailheadapps/lwc-recipes/blob/master/force-app/test/jest-mocks/lightning/uiRecordApi.js

It would make sense to have the same implementation provided here.

**Comment by trevor-bliss** [comment]
Hi @hagai-shatz. Thanks for the Issue. In general, I don't think it's a good idea to add the actual implementation for these methods because they can differ from the real code or get out of date over time. The lwc-recipe implementation is a good example of this. The real `getFieldValue` doesn't account for a `results` prop on the first param, and returns `undefined` instead of `null` if no value is found.

I guess for this one we can make an exception though since I think the functionality is unlikely to change much and it is a pain to have to copy that implementation whenever you use it. I'm going to modify what is in the lwc-recipe repo though so more closely represent what the real function does.

**Comment by hagai-shatz** [comment]
Hi @trevor-bliss 
I totally agree that services should be mocked, but it is almost impossible to test your code if utility functions like `getFieldValue` and `getFieldDisplayValue` are not implemented.
We took the code from lwc-recipe into our project to run tests and as you mentioned, it didn't work as expected, not just the `data.result` support, but also no support for string path.

This is the implementation we have now:
```javascript
	if (data) {
		const fields = fieldReference.fieldApiName ?
			[fieldReference.objectApiName].concat(fieldReference.fieldApiName.split('.')) :
			fieldReference.split('.');
		let record = data.result || data;
		if (record.apiName === fields.shift()) {
			while (record && record.fields && fields.length) {
				record = record.fields[fields.shift()];
			}
			return record && record.value;
		}
		return null;
	}
```
Following your comment, I will probably remove the support for `data.result` and `return undefined;` at the end.

Notice that we implemented similar mocking for `@salesfroce/apex/getSObjectValue`
