### ISSUE TITLE
lightning-icon error when setting title

### ISSUE THREAD

**Issue by Andy-Bigg** [salesforce/sfdx-lwc-jest#97]
The same issue is present for the lightning-icon as was present in the lightning-card, as described in this now resolved [ticket](https://github.com/salesforce/sfdx-lwc-jest/issues/57).

The following error is generated when a title tag is set on a lightning icon that is a child of a lightning card.

` console.error node_modules/@lwc/engine/dist/commonjs/es2017/engine.js:199
    [LWC error]: Invalid operation on Element [object:vm undefined (4)]. Elements created via a template should not be mutated using DOM APIs. Instead of attempting to update this element directly to change the value of attribute "title", you can update the state of the component, and let the engine to rehydrate the element accordingly.
    <lightning-icon>`

The title property should be added to the lightning-icon stub

**Comment by pmdartus** [comment]
Now that I think about it, I am uncertain that it is an issue with the stubs, but rather a bug in the engine. @Andy-Bigg can you confirm, that you can still see this error message in your console when you run your tests with the latest version of the LWC and sfdx-lwc-jest?

**Comment by trevor-bliss** [comment]
Since `title` is a global HTML attribute it shouldn't need to be an `@api` property. The linked issue for `<lightning-card>` I feel is  different because the the card component explicitly defines it's own `@api` title property to override the global default.

If this is still showing a console error I think that's an issue in the engine not in the stubs, as @pmdartus  said.
